<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Checklist</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c6084779-f3c5-4c53-b99e-3b4138e7b89f</testSuiteGuid>
   <testCaseLink>
      <guid>2a332a81-ea42-4db1-b4cc-f084b07f3de8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SignUp/MO001_SignUpA_ValidStudent_200ok</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6478e309-c90a-432a-9127-6ea60ee2b490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checklist/TCX_ChecklistAPI_GetChecklistURL</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30ce2223-2186-4d97-830c-74598b0a7d65</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf26445f-3bdf-4e60-a26a-0f88c579de64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e530c881-0985-4bed-bdf1-8ac70871b4ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Checklist/M0001_ChecklistA_GetChecklist_200ok</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eba3c5fd-dbab-45e6-9d4e-61e0dd968fd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e1f22bf-0b5d-4905-8deb-ea1ee605f9f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
